name: Update Branch Protection

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-protection:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'joshuafuller'
    steps:
      - name: Update branch protection
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Update branch protection rules to match new CI job names
          gh api -X PUT repos/${{ github.repository }}/branches/main/protection \
            --field required_status_checks='{"strict":false,"contexts":["CI Pipeline / Lint","CI Pipeline / Test","CI Pipeline / Build","CI Pipeline / Docker Build"]}' \
            --field enforce_admins=false \
            --field required_pull_request_reviews=null \
            --field restrictions=null \
            --field allow_force_pushes=false \
            --field allow_deletions=false \
            --field block_creations=false \
            --field required_conversation_resolution=false \
            --field lock_branch=false \
            --field allow_fork_syncing=false \
            --field required_linear_history=false

          echo "Branch protection updated successfully"
          echo "Required checks:"
          echo "  - CI Pipeline / Lint"
          echo "  - CI Pipeline / Test"
          echo "  - CI Pipeline / Build"
          echo "  - CI Pipeline / Docker Build"
          echo "Settings:"
          echo "  - strict: false (PRs don't need to be up-to-date)"
          echo "  - No required reviews"
          echo "  - Auto-merge enabled for repo"